  spring:
    data:
      cassandra:
        keyspace-name: container_booking
        port: 9042
        username: hzfglDAQcspiTHtWPPQASehN
        password: 4nykjPc45--IAykRaE08JAYJk4NAgAcYjG3IExeNwqjrSZnkz+QauKzNy4+OZZoOY7TqRt4u4n6FXO.lgWJEC7.OTAOc1-3Ccyvx-G3y.aGboRT4UoRF5YsDxZXRM6wB
        schema-action: create_if_not_exists
        request:
          timeout: 10s
        connection:
          connect-timeout: 10s
          init-query-timeout: 10s
    main:
        allow-circular-references: true


  datastax.astra:
    secure-connect-maersk-bundle: secure-connect-maersk.zip

  astra.db:
      id: a7c81c7c-4b94-49c7-9576-f954e7431d31-1
      region: europe-west2
      keyspace: container_booking
      application.token: AstraCS:hzfglDAQcspiTHtWPPQASehN:d04e0d98673963460dac90398be92ee54aed5f7164174da9e2266df9acf15b20

