  spring:
    data:
      cassandra:
        keyspace-name: container_booking
        port: 9042
        username: <username>
        password: <password>
        schema-action: create_if_not_exists
        request:
          timeout: 10s
        connection:
          connect-timeout: 10s
          init-query-timeout: 10s
    main:
        allow-circular-references: true


  datastax.astra:
    secure-connect-maersk-bundle: secure-connect-maersk.zip

  astra.db:
      id: <clusterid>
      region: europe-west2
      keyspace: container_booking
      application.token: <token>

